version:  "3"
services:
  ubuntu:
    container_name: snort
    hostname: snort
    user: snort
    network_mode: host
    working_dir: /home/snort/
    build: 
      context: ./
      dockerfile: Dockerfile
    image: alkeldi/snort
    environment: 
      TERM: xterm-256color
    volumes: 
      - snort_data:/etc/snort
      - snort_home:/home/snort/
      - snort_logs:/var/log/snort/
    entrypoint: /bin/sh
    tty: true

volumes:
  snort_data:
  snort_home:
  snort_logs:
